import sure
import context
import decurl.curlio as curlio
from StringIO import StringIO

def test_write_url():
    to_write = curlio.write_config('curl --url http://httpbin.org/get')
    to_write.should.equal('# This file was generated by curlio.py\nurl = "http://httpbin.org/get"\n')

def test_write_cookies():
    to_write = curlio.write_config('curl --url http://httpbin.org/get -H "Cookies: foo=bar; baz=baz2"')
    pass

def test_read_url(): 
    read_file = StringIO('# This file was generated by curlio.py\nurl = "http://httpbin.org/get"\n')
    curl_read = curlio.read_config(read_file)
    curl_read.should.equal('curl --url http://httpbin.org/get')
    pass
