import os, sys, re
import shlex
from .parser import CurlParser

def main(fname):
    sys.stdout.write(convert_from_file(fname) + '\n')

def read_config(path):
    """
    Given a path to a .curlrc file, generates and returns
    a command-line curl statement.
    """
    full_cmd = 'curl '
    with open(path, 'r') as conf:
        for line in conf.readlines():
            if len(line.strip()) > 0:
                if line.strip()[0] != '#': # if not comment line
                    line = line.strip()
                    opt_val = map(lambda x: x.strip(), line.split(' = '))
                    if len(opt_val) > 1:
                        opt, val = opt_val
                        val = val.strip('\"')
                    else:
                        opt, val = opt_val[0], None
                    if opt[0] != '-': # if not shortcut, prefix --
                        opt = '--' + opt
                    # append to full command
                    full_cmd += '{} '.format(opt)
                    full_cmd += '{} '.format(val) if val else ''
    
    return full_cmd

def write_config(curl_str):
    parser = cp.CurlParser()
    tokens = shlex.split(curl_command)
    parsed_args = parser.parse_args(tokens)

    result = '# This file was generated by {}\n'.format(os.path.basename(__file__))
    for opt, val in parsed_args:
        if val:
            result += '{} = \"{}\"\n'.format(opt, val)
        else:
            result += '{}\n'.format(opt)

    return result
   

if __name__ == '__main__':
    main(sys.argv[1])
